#!mast .ruby bin lib man qed spec test [A-Z]*.*
.ruby
lib/platypus/core_ext.rb
lib/platypus/overload.rb
lib/platypus/type.rb
lib/platypus/typecast.rb
lib/platypus/version.rb
lib/platypus.rb
qed/01_intro.rdoc
qed/02_typecast.rdoc
qed/03_type.rdoc
qed/04_overload.rdoc
test/test_overload.rb
HISTORY.rdoc
README.rdoc
NOTES.rdoc
QED.rdoc
